spring:
  config:
    import: classpath:sbshop-common.yml
  application:
    name: sbshop-worker
  jpa:
    properties:
      hibernate:
        show_sql: false
server:
  port: 8081

logging:
  level:
    com.sbshop.agent: DEBUG
    org.hibernate.dialect.Dialect: ERROR
