-- 연결 관리 DDL 적용 후, 앱 배포 전에 실행. 기존 연결·동기화 상태는 수정하지 않는다.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
CREATE TABLE IF NOT EXISTS sb_marketplus_transmission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id bigint NOT NULL REFERENCES sb_market_registration(id),
    product_id bigint NOT NULL REFERENCES sb_product(id),
    fingerprint varchar(64) NOT NULL UNIQUE,
    mall_id varchar(100) NOT NULL,
    shop_no integer NOT NULL CHECK (shop_no = 1),
    market varchar(20) NOT NULL CHECK (market IN ('GMARKET', 'AUCTION')),
    seller_account varchar(200) NOT NULL,
    cafe24_product_no varchar(30) NOT NULL,
    cafe24_product_code varchar(30) NOT NULL,
    external_id varchar(200) NOT NULL,
    transfer_type varchar(100) NOT NULL,
    outcome varchar(20) NOT NULL CHECK (outcome IN ('SUCCESS', 'FAILURE')),
    reason_code varchar(50) NOT NULL,
    detail text NOT NULL,
    requested_at timestamptz NOT NULL,
    completed_at timestamptz NOT NULL,
    captured_at timestamptz NOT NULL,
    recorded_at timestamptz NOT NULL,
    actor varchar(200) NOT NULL,
    source varchar(40) NOT NULL,
    coverage varchar(30) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_marketplus_transmission_product ON sb_marketplus_transmission(product_id, completed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_marketplus_transmission_latest ON sb_marketplus_transmission(registration_id, market, completed_at DESC);
CREATE INDEX IF NOT EXISTS ix_marketplus_transmission_operation ON sb_marketplus_transmission
    (registration_id, market, transfer_type, completed_at DESC);
COMMIT;
