-- Apply after market-inspection-multiple-markets.sql. Separate reviewed salesQuantity queue; no source stock or price reinterpretation.
CREATE TABLE IF NOT EXISTS sb_market_stock_review (
 id varchar(36) PRIMARY KEY, actor varchar(200) NOT NULL, snapshot text NOT NULL,
 created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, committed_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_stock_review_created ON sb_market_stock_review(created_at DESC);
CREATE TABLE IF NOT EXISTS sb_market_stock_task (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, review_id varchar(36) NOT NULL REFERENCES sb_market_stock_review(id),
 product_id bigint NOT NULL, sb_code varchar(255), registration_id bigint, product_revision bigint NOT NULL, registration_revision bigint NOT NULL,
 market varchar(50) NOT NULL, listing_id varchar(255), option_id varchar(255), resolved_option_id varchar(255), identifiers text, account_reference varchar(255),
 expected_quantity integer, observed_quantity integer, state varchar(30) NOT NULL, detail varchar(1000) NOT NULL,
 created_at timestamptz NOT NULL, next_run_at timestamptz NOT NULL, checked_at timestamptz, finished_at timestamptz,
 lease_token varchar(36), lease_until timestamptz, reads integer NOT NULL DEFAULT 0, writes integer NOT NULL DEFAULT 0, write_rejected boolean NOT NULL DEFAULT false, receipt varchar(1000)
);
CREATE INDEX IF NOT EXISTS ix_stock_task_due ON sb_market_stock_task(market,state,next_run_at,id);
CREATE INDEX IF NOT EXISTS ix_stock_task_review ON sb_market_stock_task(review_id,id);
CREATE INDEX IF NOT EXISTS ix_stock_task_active ON sb_market_stock_task(product_id,market,state);
CREATE TABLE IF NOT EXISTS sb_market_stock_attempt (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id bigint NOT NULL REFERENCES sb_market_stock_task(id),
 phase varchar(30) NOT NULL, detail varchar(1000) NOT NULL, recorded_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_stock_attempt_task ON sb_market_stock_attempt(task_id,id);


CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_task_active ON sb_market_stock_task(product_id,market) WHERE state IN ('CHECK','VERIFY');

ALTER TABLE sb_product_change_target ADD COLUMN IF NOT EXISTS stock_task_id bigint;
CREATE INDEX IF NOT EXISTS ix_change_target_stock_task ON sb_product_change_target(stock_task_id);
