-- Apply after market-inspection-multiple-markets.sql. New queue only; no legacy stock reinterpretation.
CREATE TABLE IF NOT EXISTS sb_market_price_review (
 id varchar(36) PRIMARY KEY, actor varchar(200) NOT NULL, snapshot text NOT NULL,
 created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, committed_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_price_review_created ON sb_market_price_review(created_at DESC);
CREATE TABLE IF NOT EXISTS sb_market_price_task (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, review_id varchar(36) NOT NULL REFERENCES sb_market_price_review(id),
 product_id bigint NOT NULL, sb_code varchar(255), registration_id bigint, product_revision bigint NOT NULL,
 market varchar(50) NOT NULL, listing_id varchar(255), option_id varchar(255), identifiers text, account_reference varchar(255),
 expected_price numeric(19,2), observed_price numeric(19,2), state varchar(30) NOT NULL, detail varchar(1000) NOT NULL,
 created_at timestamptz NOT NULL, next_run_at timestamptz NOT NULL, checked_at timestamptz, finished_at timestamptz,
 lease_token varchar(36), lease_until timestamptz, reads integer NOT NULL DEFAULT 0, writes integer NOT NULL DEFAULT 0, receipt varchar(1000)
);
CREATE INDEX IF NOT EXISTS ix_price_task_due ON sb_market_price_task(market,state,next_run_at,id);
CREATE INDEX IF NOT EXISTS ix_price_task_review ON sb_market_price_task(review_id,id);
CREATE INDEX IF NOT EXISTS ix_price_task_active ON sb_market_price_task(product_id,market,state);
CREATE TABLE IF NOT EXISTS sb_market_price_attempt (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id bigint NOT NULL REFERENCES sb_market_price_task(id),
 phase varchar(30) NOT NULL, detail varchar(1000) NOT NULL, recorded_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_price_attempt_task ON sb_market_price_attempt(task_id,id);

ALTER TABLE sb_product_change_target ADD COLUMN IF NOT EXISTS price_task_id bigint;
CREATE INDEX IF NOT EXISTS ix_change_target_price_task ON sb_product_change_target(price_task_id);
