CREATE TABLE IF NOT EXISTS sb_marketplus_public_collection (
    id VARCHAR(36) PRIMARY KEY, request_id VARCHAR(36) NOT NULL, actor VARCHAR(200) NOT NULL,
    request_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(actor, request_id)
);
CREATE INDEX IF NOT EXISTS idx_mp_public_collection_actor_time ON sb_marketplus_public_collection(actor,created_at DESC);
CREATE TABLE IF NOT EXISTS sb_marketplus_public_check (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id VARCHAR(36) NOT NULL REFERENCES sb_marketplus_public_collection(id),
    product_id BIGINT NOT NULL, sb_code VARCHAR(200), market VARCHAR(20) NOT NULL,
    target_json TEXT, mall_id VARCHAR(100), registration_revision BIGINT,
    state VARCHAR(30) NOT NULL, reason VARCHAR(1000) NOT NULL, attempts INTEGER NOT NULL,
    next_run_at TIMESTAMP WITH TIME ZONE, lease_token VARCHAR(36), worker_actor VARCHAR(200), lease_history TEXT NOT NULL DEFAULT '{}', lease_until TIMESTAMP WITH TIME ZONE,
    observation_id BIGINT REFERENCES sb_marketplus_public_observation(id), checked_at TIMESTAMP WITH TIME ZONE,
    events TEXT NOT NULL, observed_values TEXT,
    UNIQUE(collection_id,product_id,market)
);
CREATE INDEX IF NOT EXISTS idx_mp_public_check_due ON sb_marketplus_public_check(state,next_run_at,id);
INSERT INTO sb_market_inspection_gate(id,next_allowed_at) VALUES
 ('MARKETPLUS_PUBLIC_BROWSER',CURRENT_TIMESTAMP),('GMARKET_PUBLIC_READ',CURRENT_TIMESTAMP),('AUCTION_PUBLIC_READ',CURRENT_TIMESTAMP)
 ON CONFLICT (id) DO NOTHING;
