-- Apply after product-edit and market-inspection DDL. Re-running preserves reviews, attempts and leases.
CREATE TABLE IF NOT EXISTS sb_market_field_review (
 id varchar(36) PRIMARY KEY, actor varchar(200) NOT NULL,
 created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL,
 automatic boolean NOT NULL DEFAULT false, approval_consent boolean NOT NULL DEFAULT false, committed_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_field_review_actor_created ON sb_market_field_review(actor,created_at DESC);
CREATE TABLE IF NOT EXISTS sb_market_field_task (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 review_id varchar(36) NOT NULL REFERENCES sb_market_field_review(id), change_target_id bigint,
 product_id bigint NOT NULL, sb_code varchar(255), registration_id bigint,
 product_revision bigint NOT NULL, registration_revision bigint NOT NULL, market varchar(50) NOT NULL,
 listing_id varchar(255), option_id varchar(255), resolved_option_id varchar(255), identifiers text, account_reference varchar(255),
 fields text NOT NULL, expected_values text, observed_values text, prepared_payload text,
 requires_approval boolean NOT NULL DEFAULT false, observed_approval varchar(30),
 state varchar(30) NOT NULL, detail varchar(1000) NOT NULL,
 created_at timestamptz NOT NULL, next_run_at timestamptz NOT NULL, checked_at timestamptz, finished_at timestamptz,
 lease_token varchar(36), lease_until timestamptz,
 reads integer NOT NULL DEFAULT 0, writes integer NOT NULL DEFAULT 0, failures integer NOT NULL DEFAULT 0,
 write_rejected boolean NOT NULL DEFAULT false, receipt varchar(1000)
);
CREATE INDEX IF NOT EXISTS ix_field_task_due ON sb_market_field_task(market,state,next_run_at,id);
CREATE INDEX IF NOT EXISTS ix_field_task_review ON sb_market_field_task(review_id,id);
CREATE INDEX IF NOT EXISTS ix_field_task_target ON sb_market_field_task(change_target_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_field_task_active ON sb_market_field_task(product_id,market)
 WHERE state IN ('PREPARE','DRAFT','CHECK','VERIFY','AWAITING_APPROVAL');
CREATE TABLE IF NOT EXISTS sb_market_field_attempt (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id bigint NOT NULL REFERENCES sb_market_field_task(id),
 phase varchar(30) NOT NULL, detail varchar(1000) NOT NULL, observed_values text, recorded_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_field_attempt_task ON sb_market_field_attempt(task_id,id);
ALTER TABLE sb_product_change_target ADD COLUMN IF NOT EXISTS field_task_id bigint;
CREATE INDEX IF NOT EXISTS ix_change_target_field_task ON sb_product_change_target(field_task_id);
