-- 상품 편집 검토·버전·이력·마켓 미반영 기록. 운영 적용 전 백업 후 실행한다.
-- 새 코드 배포 전에 실행. 기존 상품값·마켓 연결·외부 상품번호는 변경하지 않는다.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
ALTER TABLE sb_product ADD COLUMN IF NOT EXISTS revision bigint NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS sb_product_edit_review (
    id varchar(36) PRIMARY KEY,
    actor varchar(200) NOT NULL,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    payload text NOT NULL
);
CREATE TABLE IF NOT EXISTS sb_product_change_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id varchar(36) NOT NULL,
    product_id bigint NOT NULL REFERENCES sb_product(id),
    before_revision bigint NOT NULL,
    after_revision bigint NOT NULL,
    actor varchar(200) NOT NULL,
    created_at timestamptz NOT NULL,
    changes text NOT NULL,
    review_details text NOT NULL,
    CONSTRAINT uk_product_change_review UNIQUE (review_id, product_id)
);
CREATE INDEX IF NOT EXISTS ix_product_change_history_product ON sb_product_change_history(product_id, id DESC);
CREATE TABLE IF NOT EXISTS sb_product_change_target (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id bigint NOT NULL REFERENCES sb_product_change_history(id),
    product_id bigint NOT NULL REFERENCES sb_product(id),
    registration_id bigint NOT NULL REFERENCES sb_market_registration(id),
    product_revision bigint NOT NULL,
    market varchar(50) NOT NULL,
    state varchar(30) NOT NULL,
    snapshot text NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_product_change_target_history ON sb_product_change_target(history_id);
CREATE INDEX IF NOT EXISTS ix_product_change_target_pending ON sb_product_change_target(state, id);
COMMIT;
-- 기존 이미지로 복구하더라도 이력과 revision 열을 삭제하지 않는다.
-- 가격 반영 작업자는 아직 연결하지 않았다. PENDING_DISPATCH는 외부 접수·반영 성공이 아니다.
