-- Durable vendor-wide, reviewed source/DB/market orchestration. Idempotent PostgreSQL DDL.
CREATE TABLE IF NOT EXISTS sb_supplier_batch_run (
 id VARCHAR(36) PRIMARY KEY, request_id VARCHAR(36) NOT NULL, actor VARCHAR(200) NOT NULL,
 vendor VARCHAR(20) NOT NULL, mode VARCHAR(20) NOT NULL, state VARCHAR(30) NOT NULL,
 request_payload TEXT NOT NULL, policy TEXT NOT NULL, markets TEXT NOT NULL, accounts TEXT NOT NULL DEFAULT '{}', total INTEGER NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 finished_at TIMESTAMP WITH TIME ZONE, active_item_id BIGINT, lease_token VARCHAR(36),
 lease_until TIMESTAMP WITH TIME ZONE, revision BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_supplier_batch_request UNIQUE(actor, request_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_supplier_batch_active_vendor ON sb_supplier_batch_run(vendor)
 WHERE state IN ('RUNNING','PAUSING','PAUSED');
CREATE INDEX IF NOT EXISTS ix_supplier_batch_run_due ON sb_supplier_batch_run(state,created_at);
CREATE TABLE IF NOT EXISTS sb_supplier_batch_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id VARCHAR(36) NOT NULL REFERENCES sb_supplier_batch_run(id), product_id BIGINT NOT NULL,
 sb_code VARCHAR(100), product_name VARCHAR(1000), thumbnail_url VARCHAR(2000),
 state VARCHAR(30) NOT NULL, detail VARCHAR(1000) NOT NULL, attempts INTEGER NOT NULL,
 source_snapshot_id VARCHAR(36), edit_review_id VARCHAR(36), saved_revision BIGINT, history_id BIGINT,
 calculation TEXT, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT uk_supplier_batch_product UNIQUE(batch_id,product_id)
);
CREATE INDEX IF NOT EXISTS ix_supplier_batch_item_page ON sb_supplier_batch_item(batch_id,state,id);
CREATE TABLE IF NOT EXISTS sb_supplier_batch_stage (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id VARCHAR(36) NOT NULL REFERENCES sb_supplier_batch_run(id),
 item_id BIGINT NOT NULL REFERENCES sb_supplier_batch_item(id),
 stage VARCHAR(20) NOT NULL, market VARCHAR(50) NOT NULL, field VARCHAR(20) NOT NULL,
 state VARCHAR(30) NOT NULL, detail VARCHAR(1000) NOT NULL, retryable BOOLEAN NOT NULL,
 attempts INTEGER NOT NULL, operation_id VARCHAR(36) NOT NULL, reference_id VARCHAR(36),
 target_id BIGINT, task_id BIGINT, expected VARCHAR(1000), observed VARCHAR(1000),
 started_at TIMESTAMP WITH TIME ZONE, finished_at TIMESTAMP WITH TIME ZONE,
 next_run_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT uk_supplier_batch_stage UNIQUE(item_id,stage,market,field)
);
CREATE INDEX IF NOT EXISTS ix_supplier_batch_stage_reference ON sb_supplier_batch_stage(reference_id,batch_id,stage);
CREATE INDEX IF NOT EXISTS ix_supplier_batch_stage_operation ON sb_supplier_batch_stage(operation_id,batch_id,stage);
CREATE INDEX IF NOT EXISTS ix_supplier_batch_stage_due ON sb_supplier_batch_stage(batch_id,stage,state,next_run_at,id);
CREATE TABLE IF NOT EXISTS sb_supplier_batch_attempt (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id VARCHAR(36) NOT NULL REFERENCES sb_supplier_batch_run(id), item_id BIGINT NOT NULL REFERENCES sb_supplier_batch_item(id),
 stage_id BIGINT NOT NULL REFERENCES sb_supplier_batch_stage(id), stage VARCHAR(20) NOT NULL,
 market VARCHAR(50) NOT NULL, field VARCHAR(20) NOT NULL, state VARCHAR(30) NOT NULL,
 detail VARCHAR(1000) NOT NULL, reference_id VARCHAR(36), recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_supplier_batch_attempt_item ON sb_supplier_batch_attempt(item_id,id);
-- Batch deletion removes attempts before their parent stages; these indexes keep
-- the FK checks and batch purge bounded as attempt history grows.
CREATE INDEX IF NOT EXISTS ix_supplier_batch_attempt_batch ON sb_supplier_batch_attempt(batch_id);
CREATE INDEX IF NOT EXISTS ix_supplier_batch_attempt_stage ON sb_supplier_batch_attempt(stage_id);
CREATE TABLE IF NOT EXISTS sb_supplier_batch_retry (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id VARCHAR(36) NOT NULL REFERENCES sb_supplier_batch_run(id), request_id VARCHAR(36) NOT NULL,
 actor VARCHAR(200) NOT NULL, payload TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT uk_supplier_batch_retry UNIQUE(batch_id,request_id)
);
ALTER TABLE sb_product_change_target ADD COLUMN IF NOT EXISTS batch_managed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sb_supplier_batch_run ADD COLUMN IF NOT EXISTS accounts TEXT NOT NULL DEFAULT '{}';
