-- 편집 검토 DDL(2026-09-06-product-edit-review.sql) 적용 후, 앱 배포 전에 실행.
-- 기존 삭제/오류 표지만으로 활성 연결을 해제하지 않는다. 식별자와 주문 연결은 보존한다.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
ALTER TABLE sb_market_registration ADD COLUMN IF NOT EXISTS revision bigint NOT NULL DEFAULT 0;
ALTER TABLE sb_market_registration ADD COLUMN IF NOT EXISTS connection_state varchar(32) NOT NULL DEFAULT 'LINKED';
ALTER TABLE sb_market_registration ADD COLUMN IF NOT EXISTS gmarket_connection_state varchar(32) NOT NULL DEFAULT 'LINKED';
ALTER TABLE sb_market_registration ADD COLUMN IF NOT EXISTS auction_connection_state varchar(32) NOT NULL DEFAULT 'LINKED';
CREATE TABLE IF NOT EXISTS sb_market_connection_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id bigint NOT NULL REFERENCES sb_market_registration(id),
    product_id bigint NOT NULL REFERENCES sb_product(id),
    market varchar(50) NOT NULL,
    external_id varchar(200) NOT NULL,
    actor varchar(200) NOT NULL,
    source varchar(40) NOT NULL,
    result varchar(40) NOT NULL,
    observed_state varchar(40) NOT NULL,
    observed_at timestamptz NOT NULL,
    recorded_at timestamptz NOT NULL,
    reviewed_revision bigint NOT NULL,
    evidence text NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_market_connection_event_product ON sb_market_connection_event(product_id, id DESC);
CREATE INDEX IF NOT EXISTS ix_market_connection_event_registration ON sb_market_connection_event(registration_id, id DESC);
CREATE INDEX IF NOT EXISTS ix_product_change_target_connection ON sb_product_change_target(registration_id, market, state);
COMMIT;
