-- 편집 검토 → 연결 수명주기 DDL 이후, 새 API/worker 배포 전에 실행.
-- 사용자 선택으로 접수한 조회 작업만 처리한다. 전체 상품을 자동 등록하는 데이터 변경은 없다.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
CREATE TABLE IF NOT EXISTS sb_market_inspection_batch (
    id varchar(36) PRIMARY KEY,
    actor varchar(200) NOT NULL,
    request_identity text NOT NULL,
    source varchar(50) NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS sb_market_inspection_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id varchar(36) NOT NULL REFERENCES sb_market_inspection_batch(id),
    -- 미존재 상품도 제외 사유를 기록하므로 product_id FK는 만들지 않는다.
    product_id bigint NOT NULL,
    sb_code varchar(100),
    registration_id bigint REFERENCES sb_market_registration(id),
    registration_revision bigint NOT NULL,
    external_id varchar(200),
    identifiers text,
    account_reference varchar(200),
    state varchar(30) NOT NULL,
    attempts integer NOT NULL,
    next_run_at timestamptz NOT NULL,
    lease_token varchar(36),
    lease_until timestamptz,
    event_id bigint REFERENCES sb_market_connection_event(id),
    code varchar(200),
    detail varchar(1000),
    observed_state varchar(40),
    updated_at timestamptz NOT NULL,
    UNIQUE (batch_id, product_id)
);
CREATE TABLE IF NOT EXISTS sb_market_inspection_gate (
    id varchar(50) PRIMARY KEY,
    lease_token varchar(36),
    lease_until timestamptz,
    next_allowed_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_market_inspection_batch_created ON sb_market_inspection_batch(created_at DESC);
CREATE INDEX IF NOT EXISTS ix_market_inspection_task_due ON sb_market_inspection_task(state, next_run_at);
CREATE INDEX IF NOT EXISTS ix_market_inspection_task_lease ON sb_market_inspection_task(state, lease_until);
CREATE INDEX IF NOT EXISTS ix_market_inspection_task_product ON sb_market_inspection_task(product_id, state);
CREATE INDEX IF NOT EXISTS ix_market_inspection_task_batch ON sb_market_inspection_task(batch_id, id);
COMMIT;
