CREATE TABLE IF NOT EXISTS sb_marketplus_public_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint VARCHAR(64) NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    product_revision BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    market VARCHAR(20) NOT NULL,
    mall_id VARCHAR(100) NOT NULL,
    seller_account VARCHAR(200) NOT NULL,
    cafe24_product_no VARCHAR(30) NOT NULL,
    cafe24_product_code VARCHAR(30) NOT NULL,
    external_id VARCHAR(200) NOT NULL,
    source_url VARCHAR(500) NOT NULL,
    observed_values TEXT NOT NULL,
    quantity_basis VARCHAR(40) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor VARCHAR(200) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mp_public_observation_product_time
    ON sb_marketplus_public_observation (product_id, captured_at DESC, id DESC);
