dependencies {
    implementation project(':core')
    implementation project(':infrastructure')
    
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    
    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'
}
